### ISSUE TITLE
Odra 0.1.0 Milestone

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#2]
### Repos:
- [x] odra
- [x] odra-casper
- [ ] cargo-odra
- [x] odra-template
- [ ] odra-examples

### [KUBA] Cargo Odra
- [x] `cargo odra build` without params should be the same as `cargo odra build -h`.
- [x] remove "near"
- [x] cargo odra clean
- [x] inform where wasm files were copied
- [x] cargo fmt on *wasm.rs
- [x] read how to cargo install cargo-odra
- [x] detect missing wasm-strip
- [ ] ~~detect missing target wasm32-unknown-unknown~~
- [x] Github Actions
- [x] Developer mode
- [x] setup repo:
    - master restructed
    - develop restricted
    - feature
- [x] README.md
- [x] CHANGELOG.md
- [ ] Docsy for every public element.
- [x] add MIT LICENCE
- [x] Allow for odra and backend at a spec directory in developer mode.
- [x] [MACIEJ] refactor cargo odra generate.

### [MACIEJ] Odra Casper
- [x] rename is_named_arg_exist,
- [x] TODO: Optimalize get_key and set_key
- [x] Remove OdraAddressWrapper and impl CasperAddress::from_odra_address(), casper_address.to_odra_address().
- [x] ~~Fix WrappedType~~
- [x] add MIT LICENCE
- [x] CHANGELOG.md
- [x] setup repo:
    - master restructed
    - develop restricted
    - feature
- [x] remove features 
- [x] Enable Github Actions
- [x] Tests for codegen.
- [x] Docs for public elements.
- [x] OdraError to OdraExecutionError when is implemented.

### [KUBA] Odra Template
- [x] make sure it works.
- [x] CHANGELOG.md
- [x] Docsy for every public element.
- [x] ~~add MIT LICENCE~~
- [x] setup repo:
    - master restructed
    - develop restricted
    - feature

### [KUBA] Owned Token
- [x] Prepare reposiotry for publishing
- [x] Rename to odra-examples
- [x] README
- [x] CHANGELOG.md
- [x] add MIT LICENCE
- [x] setup repo:
    - master restructed
    - develop restricted
    - feature
- [x] Enable Casper tests when `cargo odra test -p casper` compiles `getter_proxy`. 
- [x] Use Error macro when available.

### [KRZYSIEK] Odra
- [x] Introduce unwrap_or_revert(err: Into<OdraError>)
- [x] unify event_absolute_position and index_to_usize, use odra-utils
- [x] try &str instead of &[u8] in core/contract_env
- [x] Fix TODO: odra/lang/ir/src/module_item/module_impl.rs.
- [x] Fix TODO in variable and mapping
- [x] add MIT LICENCE
- [x] remove mock_vm/src/test_utils.rs
- [x] setup repo:
    - master restructed
    - develop restricted
    - feature
- [x] Enable Github Actions
- [x] Add ContractEnv::self_address() to both MockVM and external_api::ContractEnv.
- [x] [MACIEJ] modify assert_event to work backwards
- [x] Docsy for every public element.
- [x] Macro for errors.
- [x] CHANGELOG.md
- [x] [MACIEJ] README.md per directory if needed
- [x] [MACIEJ] Main README.md

##### Odra
- [x] publish odra 0.0.1
- [x] make remaining changes (README and changlog) and change to 0.1.0.
- [ ] make new tag, observe release.

##### Odra Casper
- [x] change to use odra 0.0.1
- [x] publish odra-casper 0.0.1
- [x] make remaining changes (changlog, docs) and change to 0.1.0.
- [ ] make new tag, observe release.

##### Odra Template
- [x] change to use odra 0.0.1
- [x] point at odra 0.1.0

##### Cargo Odra
- [x] change to use odra 0.0.1
- [x] publish 0.0.1
- [ ] make remaining changes (changlog) and change to 0.1.0.
- [ ] make new tag, observe release.

##### Odra Examples
- [x] point at odra 0.0.1
- [x] enable casper tests
- [x] point at odra 0.1.0

### Publishing
- [x] Set all version to 0.0.1.
- [ ] Test publish with 0.0.1 to 0.0.2
- [x] merge all develops to master
- [ ] publishing GH Actions
- [ ] Video
- [x] DxD Portal Milestone submit
- [x] Make sure CRDAO is on it.
- [x] Update odra.dev
- [x] Add "Proudly by odra.dev (R) and logo and link"
- [x] Open discord.
- [ ] Write release blog post at odra.dev/blog

### Cargo.toml example
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra" // set to proper 
description = "High-level smart contract framework for Rust" // different for each. This one is for core.
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]

**Comment by zie1ony** [comment]
Odra 0.1.0 released with success :)
