### ISSUE TITLE
Tracking issue for the `0.8.0` documentation.

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#315]
Things to document:
- [x] Update `README.md`.
- [x] Update `README.md` in `cargo-odra`.
- [x] #313
- [x] Explain new storage layout and keys creation algorithm.
- [x] Add all required in-code comments.
- [x] Update `odra.dev/docs`.
- [x] Update `CHANGELOG.md`.
