### ISSUE TITLE
Final 1.0.0 TODO

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#429]
- [x] Changelog update
- [x] CEP18 Tutorial
- [x] CEP78 Tutorial
- [x] Check docs code
- [ ] Release Docs
- [x] Update crates version
- [x] Prepare release note
- [x] Release 1.0.0-rc
- [ ] Release cargo-odra
- [x] Fix lack of README.md on crates.io (https://crates.io/crates/odra/0.9.1)
- [x] Update ROADMAP.md
- [ ] Update logo

**Comment by kubaplas** [comment]
Done.
